### ISSUE TITLE
您好 关于安卓9.0以上的问题

### ISSUE THREAD

**Issue by gitldy1013** [oott123/SMSPoster#2]
实在不好意思 知道这个项目不维护了 可是因为确实现在有这个需求的原因 我本身安卓开发也不怎么了解 想问一下开发者 能不能提供一下新版本的代码 或者点播一二 感谢~！不知道您是不是用eclipse开发的 这个项目应该是14年的了吧。。哈哈 实在尴尬

**Comment by oott123** [comment]
因为不维护了，所以没有新版本代码可以提供。

请尝试同类项目：

https://github.com/telegram-sms/telegram-sms
https://github.com/ushahidi/SMSSync

**Comment by gitldy1013** [comment]
好的 感谢





---原始邮件---
发件人: "三三"<notifications@github.com&gt;
发送时间: 2020年10月19日(周一) 下午5:16
收件人: "oott123/SMSPoster"<SMSPoster@noreply.github.com&gt;;
抄送: "有梦想的咸鱼"<1126176532@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [oott123/SMSPoster] 您好 关于安卓9.0以上的问题 (#2)




 
因为不维护了，所以没有新版本代码可以提供。
 
请尝试同类项目：
 
https://github.com/telegram-sms/telegram-sms
 https://github.com/ushahidi/SMSSync
